package com.weavx.web.utils;

public enum PaymentStatuses {
	PAYMENT_IN_PROGRESS("PAYMENT_IN_PROGRESS"),
	PAYMENT_DENIED("PAYMENT_DENIED"),
	PAYMENT_ERROR("PAYMENT_ERROR"),
	CHARGED("CHARGED"),
	SUCCESS_TX("SUCCESS_TX"),
	FAILED_TX("FAILED_TX"),
	ABORTED("ABORTED"),
	NOT_PROVISIONED("NOT_PROVISIONED"),
	IN_BLACKLIST("IN_BLACKLIST"),
	USER_EXPIRED_ACCESS("USER_EXPIRED_ACCESS"),
	FRAUD_REPORTED("FRAUD_REPORTED"),
	CANCEL_REFUND("CANCEL_REFUND"),
	SPLIT_SUCCESS("SPLIT_SUCCESS"),
	SPLIT_IN_PROGRESS("SPLIT_IN_PROGRESS"),
	SPLIT_EXPIRED_ACCESS("SPLIT_EXPIRED_ACCESS"),
	SPLIT_ABORTED("SPLIT_ABORTED"),
	SPLIT_FRAUD_REPORTED("SPLIT_FRAUD_REPORTED"),
	SPLIT_REFUND("SPLIT_REFUND"),
	SUBSCRIPTION_CANCEL("SUBSCRIPTION_CANCEL");
	
	private String status;
	
	private PaymentStatuses (String status) {
		this.status = status;
	}
	
	public String getStatus() {
		return status;
	}
	
}
